# Generated by Django 6.0.4 on 2026-05-02 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_codigorecuperacion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='espacioparqueo',
            options={'ordering': ['zona', 'numero']},
        ),
        migrations.AddField(
            model_name='espacioparqueo',
            name='zona',
            field=models.CharField(choices=[('A', 'Zona A'), ('B', 'Zona B'), ('C', 'Zona C'), ('D', 'Zona D')], default='A', max_length=1),
        ),
        migrations.AlterField(
            model_name='espacioparqueo',
            name='tipo',
            field=models.CharField(choices=[('estandar', 'Estándar'), ('discapacitado', 'Discapacitado')], default='estandar', max_length=50),
        ),
    ]
