# Generated by Django 6.0.4 on 2026-05-03 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_add_zona_to_espacio'),
    ]

    operations = [
        migrations.AddField(
            model_name='espacioparqueo',
            name='duracion_mantenimiento',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='espacioparqueo',
            name='motivo_mantenimiento',
            field=models.TextField(blank=True, null=True),
        ),
    ]
