# Generated by Django 6.0.4 on 2026-05-17 18:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_espacioparqueo_duracion_mantenimiento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Billetera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldo', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='billetera', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'billetera',
            },
        ),
        migrations.CreateModel(
            name='Recarga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('metodo', models.CharField(choices=[('bancolombia', 'Bancolombia'), ('nequi', 'Nequi'), ('visa', 'Visa'), ('otro', 'Otro')], max_length=20)),
                ('estado', models.CharField(choices=[('exitosa', 'Exitosa'), ('pendiente', 'Pendiente'), ('fallida', 'Fallida')], default='exitosa', max_length=20)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('billetera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recargas', to='core.billetera')),
            ],
            options={
                'db_table': 'recarga',
                'ordering': ['-fecha'],
            },
        ),
    ]
