# Generated by Django 6.0.4 on 2026-05-31 14:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_billetera_recarga'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehiculos', to=settings.AUTH_USER_MODEL),
        ),
    ]
