# Generated by Django 6.0.4 on 2026-06-05 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_vehiculo_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='metodo',
            field=models.CharField(choices=[('tarjeta', 'Tarjeta'), ('app', 'App')], max_length=20),
        ),
    ]
