# Generated by Django 6.0.4 on 2026-06-05 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_pago_metodo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='metodo',
            field=models.CharField(choices=[('tarjeta', 'Tarjeta'), ('app', 'App'), ('excepcion', 'Excepción')], max_length=20),
        ),
    ]
