# Generated by Django 6.0.4 on 2026-06-06 02:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_pago_metodo'),
    ]

    operations = [
        migrations.AddField(
            model_name='autorizacionexcepcional',
            name='pago',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='autorizacion', to='core.pago'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='metodo',
            field=models.CharField(choices=[('tarjeta', 'Tarjeta'), ('app', 'App'), ('excepcion', 'Excepciones')], max_length=20),
        ),
    ]
